# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  version-checking:
    name: "version-checking"
    runs-on: windows-latest
    if: ${{ github.event.pull_request.merged && github.head_ref == 'dev' }}
    outputs:
      output1: ${{ steps.package-json.outputs.has-updated }}
      output2: ${{ steps.package-json.outputs.previous-version }}
      output3: ${{ steps.package-json.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: johnnybenson/package-json-versioned-action@v1.0.5
        id: package-json
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

  build:
    name: "build & publish"
    runs-on: windows-latest
    needs: checking
    if: ${{ needs.test.outputs.output2 != needs.test.outputs.output3 }}
    steps:
      - name: auto taging
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          tag_prefix: "v"
          package_root: "./"
      - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          build_script_name: github-full-build
          args: "-p always"
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

  canceled:
    name: "Cancel"
    runs-on: windows-latest
    needs: checking
    if: ${{ needs.test.outputs.output2 == needs.test.outputs.output3 }}
    steps:
      - uses: vishnudxb/cancel-workflow@v1.2
        with:
          repo: huibizhang/photolisting
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}
